// SUBSEQUENCES OF STRING

// You are given a string 'STR' containing lowercase English letters from a to z inclusive . Your task is to find all non-empty possible subsequences of 'STR'

// A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order .



#include <iostream>
#include <vector>
using namespace std;


class Solution{

private :
    void solve(string str , string output , int index , vector<string>& ans)
    {
        // base case
        if (index >= str.length())
        {
            ans.push_back(output);
            return ;
        }

        // exclude 
        solve(str , output , index+1 , ans);

        // include
        char element = str[index];
        output.push_back(element);
        solve(str , output , index+1 , ans);
    }


public : 
    vector<string> subsequences(string str)
    {
        vector<string> ans ;
        string output = "";
        int index = 0 ;

        solve(str , output , index , ans);

        return ans ;
    }

};


void Print_vector(vector<string> v)
{
    int size = v.size() ;
    for (int i = 0 ; i < size ; i++)
    {
        cout<<"\""<<v[i]<<"\""<<endl;
    }
}


int main() {
    Solution sol ;

    string str = "abc";

    vector<string> Subsequences = sol.subsequences(str);

    Print_vector(Subsequences);

    return 0;
}





